[pytest]
addopts = -s -v
python_files = test_*.py *_test.py
python_classes = Test*
python_functions = test_*
markers =
    users: Marks all tests related to users
    files: Marks all tests related to files
    regression: Marks all regression tests
    smoke: Marks all smoke tests
    critical: Marks all critical tests
    api: Marks all api tests
    fast: Marks all fast tests
    slow: Marks all slow tests

